extends RefCounted

const DEFAULT_BIOME_ID := 3
const TEXTURE_ROOT := "res://assets/textures/terrain"

const BEACH_ALBEDO := "%s/beach/aerial_beach_01_diff_1k.jpg" % TEXTURE_ROOT
const BEACH_HEIGHT := "%s/beach/aerial_beach_01_disp_1k.png" % TEXTURE_ROOT
const COASTAL_PLAIN_ALBEDO := "%s/coastal_plain/coastal_plain_sandy_loam_diff_1k.jpg" % TEXTURE_ROOT
const COASTAL_PLAIN_HEIGHT := "%s/coastal_plain/coastal_plain_sandy_loam_disp_1k.png" % TEXTURE_ROOT
const COASTAL_PLAIN_SPOTS_ALBEDO := "%s/coastal_plain/coastal_plain_kurkar_scrub_spots_diff_1k.jpg" % TEXTURE_ROOT
const COASTAL_PLAIN_SPOTS_HEIGHT := "%s/coastal_plain/coastal_plain_kurkar_scrub_spots_disp_1k.png" % TEXTURE_ROOT
const COASTAL_PLAIN_PATH_ALBEDO := "%s/coastal_plain/coastal_plain_compacted_path_diff_1k.jpg" % TEXTURE_ROOT
const COASTAL_PLAIN_PATH_HEIGHT := "%s/coastal_plain/coastal_plain_compacted_path_disp_1k.png" % TEXTURE_ROOT
const COASTAL_PLAIN_ROCK_ALBEDO := "%s/coastal_plain/coastal_plain_kurkar_rock_diff_1k.jpg" % TEXTURE_ROOT
const COASTAL_PLAIN_ROCK_HEIGHT := "%s/coastal_plain/coastal_plain_kurkar_rock_disp_1k.png" % TEXTURE_ROOT
const FOREST_ALBEDO := "%s/forest_ground/forrest_ground_01_diff_1k.jpg" % TEXTURE_ROOT
const FOREST_HEIGHT := "%s/forest_ground/forrest_ground_01_disp_1k.png" % TEXTURE_ROOT
const MUD_ALBEDO := "%s/mud/brown_mud_leaves_01_diff_1k.jpg" % TEXTURE_ROOT
const MUD_HEIGHT := "%s/mud/brown_mud_leaves_01_disp_1k.png" % TEXTURE_ROOT
const CRACKED_MUD_ALBEDO := "%s/mud_cracked/mud_cracked_dry_03_diff_1k.jpg" % TEXTURE_ROOT
const CRACKED_MUD_HEIGHT := "%s/mud_cracked/mud_cracked_dry_03_disp_1k.png" % TEXTURE_ROOT
const ROCKY_GRASS_ALBEDO := "%s/rocky_grass/rocky_terrain_02_diff_1k.jpg" % TEXTURE_ROOT
const ROCKY_GRASS_HEIGHT := "%s/rocky_grass/rocky_terrain_02_disp_1k.png" % TEXTURE_ROOT
const ROCKY_GRAVEL_ALBEDO := "%s/rocky_gravel/gravelly_sand_diff_1k.jpg" % TEXTURE_ROOT
const ROCKY_GRAVEL_HEIGHT := "%s/rocky_gravel/gravelly_sand_disp_1k.png" % TEXTURE_ROOT
const BETHLEHEM_HIGHLAND_ALBEDO := "%s/shephelah_mediterranean/bethlehem_highland_green_diff_1k.jpg" % TEXTURE_ROOT
const BETHLEHEM_HIGHLAND_HEIGHT := "%s/shephelah_mediterranean/bethlehem_highland_green_disp_1k.png" % TEXTURE_ROOT
const SHEPHELAH_MEDITERRANEAN_ALBEDO := "%s/shephelah_mediterranean/shephelah_terra_rossa_limestone_diff_1k.jpg" % TEXTURE_ROOT
const SHEPHELAH_MEDITERRANEAN_HEIGHT := "%s/shephelah_mediterranean/shephelah_terra_rossa_limestone_disp_1k.png" % TEXTURE_ROOT
const SHEPHELAH_SPOTS_ALBEDO := "%s/shephelah_mediterranean/shephelah_scrub_spots_diff_1k.jpg" % TEXTURE_ROOT
const SHEPHELAH_SPOTS_HEIGHT := "%s/shephelah_mediterranean/shephelah_scrub_spots_disp_1k.png" % TEXTURE_ROOT
const SHEPHELAH_PATH_ALBEDO := "%s/shephelah_mediterranean/shephelah_compacted_path_diff_1k.jpg" % TEXTURE_ROOT
const SHEPHELAH_PATH_HEIGHT := "%s/shephelah_mediterranean/shephelah_compacted_path_disp_1k.png" % TEXTURE_ROOT
const SHEPHELAH_ROCK_ALBEDO := "%s/shephelah_mediterranean/shephelah_limestone_rock_diff_1k.jpg" % TEXTURE_ROOT
const SHEPHELAH_ROCK_HEIGHT := "%s/shephelah_mediterranean/shephelah_limestone_rock_disp_1k.png" % TEXTURE_ROOT
const CENTRAL_HIGHLANDS_ALBEDO := "%s/central_highlands/central_highlands_ridge_ground_diff_1k.jpg" % TEXTURE_ROOT
const CENTRAL_HIGHLANDS_HEIGHT := "%s/central_highlands/central_highlands_ridge_ground_disp_1k.png" % TEXTURE_ROOT
const CENTRAL_HIGHLANDS_SPOTS_ALBEDO := "%s/central_highlands/central_highlands_rocky_spots_diff_1k.jpg" % TEXTURE_ROOT
const CENTRAL_HIGHLANDS_SPOTS_HEIGHT := "%s/central_highlands/central_highlands_rocky_spots_disp_1k.png" % TEXTURE_ROOT
const CENTRAL_HIGHLANDS_PATH_ALBEDO := "%s/central_highlands/central_highlands_worn_path_diff_1k.jpg" % TEXTURE_ROOT
const CENTRAL_HIGHLANDS_PATH_HEIGHT := "%s/central_highlands/central_highlands_worn_path_disp_1k.png" % TEXTURE_ROOT
const CENTRAL_HIGHLANDS_ROCK_ALBEDO := "%s/central_highlands/central_highlands_limestone_rock_diff_1k.jpg" % TEXTURE_ROOT
const CENTRAL_HIGHLANDS_ROCK_HEIGHT := "%s/central_highlands/central_highlands_limestone_rock_disp_1k.png" % TEXTURE_ROOT
const GALILEE_HILLS_ALBEDO := "%s/galilee_northern_hills/galilee_hills_leafy_ground_diff_1k.jpg" % TEXTURE_ROOT
const GALILEE_HILLS_HEIGHT := "%s/galilee_northern_hills/galilee_hills_leafy_ground_disp_1k.png" % TEXTURE_ROOT
const GALILEE_HILLS_SPOTS_ALBEDO := "%s/galilee_northern_hills/galilee_hills_maquis_spots_diff_1k.jpg" % TEXTURE_ROOT
const GALILEE_HILLS_SPOTS_HEIGHT := "%s/galilee_northern_hills/galilee_hills_maquis_spots_disp_1k.png" % TEXTURE_ROOT
const GALILEE_HILLS_PATH_ALBEDO := "%s/galilee_northern_hills/galilee_hills_terra_rossa_path_diff_1k.jpg" % TEXTURE_ROOT
const GALILEE_HILLS_PATH_HEIGHT := "%s/galilee_northern_hills/galilee_hills_terra_rossa_path_disp_1k.png" % TEXTURE_ROOT
const GALILEE_HILLS_ROCK_ALBEDO := "%s/galilee_northern_hills/galilee_hills_limestone_rock_diff_1k.jpg" % TEXTURE_ROOT
const GALILEE_HILLS_ROCK_HEIGHT := "%s/galilee_northern_hills/galilee_hills_limestone_rock_disp_1k.png" % TEXTURE_ROOT
const JORDAN_RIFT_ALBEDO := "%s/jordan_rift/jordan_rift_alluvial_silt_diff_1k.jpg" % TEXTURE_ROOT
const JORDAN_RIFT_HEIGHT := "%s/jordan_rift/jordan_rift_alluvial_silt_disp_1k.png" % TEXTURE_ROOT
const JORDAN_RIFT_SPOTS_ALBEDO := "%s/jordan_rift/jordan_rift_marl_crust_spots_diff_1k.jpg" % TEXTURE_ROOT
const JORDAN_RIFT_SPOTS_HEIGHT := "%s/jordan_rift/jordan_rift_marl_crust_spots_disp_1k.png" % TEXTURE_ROOT
const JORDAN_RIFT_PATH_ALBEDO := "%s/jordan_rift/jordan_rift_dusty_path_diff_1k.jpg" % TEXTURE_ROOT
const JORDAN_RIFT_PATH_HEIGHT := "%s/jordan_rift/jordan_rift_dusty_path_disp_1k.png" % TEXTURE_ROOT
const JORDAN_RIFT_ROCK_ALBEDO := "%s/jordan_rift/jordan_rift_marl_limestone_rock_diff_1k.jpg" % TEXTURE_ROOT
const JORDAN_RIFT_ROCK_HEIGHT := "%s/jordan_rift/jordan_rift_marl_limestone_rock_disp_1k.png" % TEXTURE_ROOT
const TRANSJORDAN_PLATEAU_ALBEDO := "%s/transjordan_plateau/transjordan_plateau_rocky_steppe_diff_1k.jpg" % TEXTURE_ROOT
const TRANSJORDAN_PLATEAU_HEIGHT := "%s/transjordan_plateau/transjordan_plateau_rocky_steppe_disp_1k.png" % TEXTURE_ROOT
const TRANSJORDAN_PLATEAU_SPOTS_ALBEDO := "%s/transjordan_plateau/transjordan_plateau_chert_spots_diff_1k.jpg" % TEXTURE_ROOT
const TRANSJORDAN_PLATEAU_SPOTS_HEIGHT := "%s/transjordan_plateau/transjordan_plateau_chert_spots_disp_1k.png" % TEXTURE_ROOT
const TRANSJORDAN_PLATEAU_PATH_ALBEDO := "%s/transjordan_plateau/transjordan_plateau_gravel_path_diff_1k.jpg" % TEXTURE_ROOT
const TRANSJORDAN_PLATEAU_PATH_HEIGHT := "%s/transjordan_plateau/transjordan_plateau_gravel_path_disp_1k.png" % TEXTURE_ROOT
const TRANSJORDAN_PLATEAU_ROCK_ALBEDO := "%s/transjordan_plateau/transjordan_plateau_chert_limestone_rock_diff_1k.jpg" % TEXTURE_ROOT
const TRANSJORDAN_PLATEAU_ROCK_HEIGHT := "%s/transjordan_plateau/transjordan_plateau_chert_limestone_rock_disp_1k.png" % TEXTURE_ROOT
const NEGEV_ARABAH_ALBEDO := "%s/negev_arabah_wilderness/negev_arabah_desert_pavement_diff_1k.jpg" % TEXTURE_ROOT
const NEGEV_ARABAH_HEIGHT := "%s/negev_arabah_wilderness/negev_arabah_desert_pavement_disp_1k.png" % TEXTURE_ROOT
const NEGEV_ARABAH_SPOTS_ALBEDO := "%s/negev_arabah_wilderness/negev_arabah_wadi_fan_spots_diff_1k.jpg" % TEXTURE_ROOT
const NEGEV_ARABAH_SPOTS_HEIGHT := "%s/negev_arabah_wilderness/negev_arabah_wadi_fan_spots_disp_1k.png" % TEXTURE_ROOT
const NEGEV_ARABAH_PATH_ALBEDO := "%s/negev_arabah_wilderness/negev_arabah_compacted_path_diff_1k.jpg" % TEXTURE_ROOT
const NEGEV_ARABAH_PATH_HEIGHT := "%s/negev_arabah_wilderness/negev_arabah_compacted_path_disp_1k.png" % TEXTURE_ROOT
const NEGEV_ARABAH_ROCK_ALBEDO := "%s/negev_arabah_wilderness/negev_arabah_limestone_flint_rock_diff_1k.jpg" % TEXTURE_ROOT
const NEGEV_ARABAH_ROCK_HEIGHT := "%s/negev_arabah_wilderness/negev_arabah_limestone_flint_rock_disp_1k.png" % TEXTURE_ROOT
const STONE_ALBEDO := "%s/marble/marble_rock_02_diff_1k.jpg" % TEXTURE_ROOT
const STONE_HEIGHT := "%s/marble/marble_rock_02_disp_1k.png" % TEXTURE_ROOT

const PROFILES := {
	1: {
		"biome_key": "coastal_plain",
		"name": "Coastal plain",
		"primary_albedo_path": COASTAL_PLAIN_ALBEDO,
		"primary_height_path": COASTAL_PLAIN_HEIGHT,
		"secondary_albedo_path": COASTAL_PLAIN_SPOTS_ALBEDO,
		"secondary_height_path": COASTAL_PLAIN_SPOTS_HEIGHT,
		"path_albedo_path": COASTAL_PLAIN_PATH_ALBEDO,
		"path_height_path": COASTAL_PLAIN_PATH_HEIGHT,
		"rock_albedo_path": COASTAL_PLAIN_ROCK_ALBEDO,
		"rock_height_path": COASTAL_PLAIN_ROCK_HEIGHT,
		"primary_tint": "#e5cf9b",
		"secondary_tint": "#b5ac7a",
		"path_tint": "#d4bb88",
		"detail_tile": 6.1,
		"secondary_tile_scale": 1.02,
		"path_tile_scale": 0.84,
		"secondary_mask_strength": 0.62,
		"roughness_primary": 0.94,
		"roughness_secondary": 0.97,
		"roughness_path": 0.98,
		"normal_depth": 0.46,
		"spot_edge_raggedness": 0.36,
		"spot_breakup_strength": 0.40,
		"spot_grain_strength": 0.14,
		"spot_core_strength": 0.18,
		"terrain_height_scale": 0.42,
		"terrain_ridge_strength": 0.26,
		"terrain_swell_strength": 0.48,
		"terrain_wadi_strength": 0.44,
		"terrain_ripple_strength": 0.34,
		"terrain_outer_hill_strength": 0.18,
		"terrain_floor": -0.34,
		"terrain_height_offset": -0.03,
		"surface_relief_strength": 0.62,
		"secondary_surface_drop": 0.035,
		"path_color": "#c9ad70",
		"path_width": 2.8,
		"path_feather": 1.4,
		"path_edge_noise": 0.62,
		"rock_count": 108,
		"rock_scale": 0.58,
		"rock_color": "#bcae8d",
		"rock_texture_tile": 0.52,
		"rock_roughness": 0.98,
		"clump_count": 120,
		"clump_color": "#738755",
		"clump_height": 0.34,
		"clump_radius": 0.10,
		"wadi_count": 0,
		"sky_color": "#80c6f0",
		"fog_color": "#d5e4dc",
		"fog_density": 0.0036,
		"ambient_color": "#eee3c6",
		"ambient_energy": 0.62,
		"sun_color": "#fff1c8",
		"sun_energy": 2.65,
		"fill_color": "#aad1ec",
		"fill_energy": 0.34,
		"underlay_color": "#b99e66"
	},
	2: {
		"biome_key": "shephelah_foothills",
		"name": "Shephelah foothills",
		"primary_albedo_path": BETHLEHEM_HIGHLAND_ALBEDO,
		"primary_height_path": BETHLEHEM_HIGHLAND_HEIGHT,
		"secondary_albedo_path": SHEPHELAH_SPOTS_ALBEDO,
		"secondary_height_path": SHEPHELAH_SPOTS_HEIGHT,
		"path_albedo_path": SHEPHELAH_PATH_ALBEDO,
		"path_height_path": SHEPHELAH_PATH_HEIGHT,
		"rock_albedo_path": SHEPHELAH_ROCK_ALBEDO,
		"rock_height_path": SHEPHELAH_ROCK_HEIGHT,
		"primary_tint": "#d4d7a9",
		"secondary_tint": "#aeb782",
		"path_tint": "#d9b077",
		"detail_tile": 6.0,
		"secondary_tile_scale": 1.04,
		"path_tile_scale": 0.86,
		"secondary_mask_strength": 0.70,
		"roughness_primary": 0.94,
		"roughness_secondary": 0.97,
		"roughness_path": 0.98,
		"normal_depth": 0.64,
		"spot_edge_raggedness": 0.42,
		"spot_breakup_strength": 0.48,
		"spot_grain_strength": 0.16,
		"spot_core_strength": 0.26,
		"terrain_height_scale": 1.12,
		"terrain_ridge_strength": 1.18,
		"terrain_swell_strength": 1.05,
		"terrain_wadi_strength": 1.32,
		"terrain_ripple_strength": 0.78,
		"terrain_outer_hill_strength": 0.92,
		"terrain_floor": -0.82,
		"terrain_height_offset": 0.18,
		"surface_relief_strength": 1.02,
		"secondary_surface_drop": 0.04,
		"path_color": "#b89255",
		"path_width": 2.45,
		"path_feather": 1.55,
		"path_edge_noise": 0.78,
		"rock_count": 285,
		"rock_scale": 0.76,
		"rock_color": "#b7ac90",
		"rock_texture_tile": 0.48,
		"rock_roughness": 0.98,
		"clump_count": 270,
		"clump_color": "#4f783b",
		"clump_height": 0.34,
		"clump_radius": 0.11,
		"wadi_count": 2,
		"wadi_width": 4.1,
		"wadi_color": "#8f7b56",
		"wadi_alpha": 0.38,
		"sky_color": "#70b9ee",
		"fog_color": "#c6d5c3",
		"fog_density": 0.0046,
		"ambient_color": "#dfe5c4",
		"ambient_energy": 0.61,
		"sun_color": "#ffe6ad",
		"sun_energy": 2.72,
		"fill_color": "#9bc6e7",
		"fill_energy": 0.36,
		"underlay_color": "#657948"
	},
	3: {
		"biome_key": "central_highlands",
		"name": "Central highlands",
		"primary_albedo_path": CENTRAL_HIGHLANDS_ALBEDO,
		"primary_height_path": CENTRAL_HIGHLANDS_HEIGHT,
		"secondary_albedo_path": CENTRAL_HIGHLANDS_SPOTS_ALBEDO,
		"secondary_height_path": CENTRAL_HIGHLANDS_SPOTS_HEIGHT,
		"path_albedo_path": CENTRAL_HIGHLANDS_PATH_ALBEDO,
		"path_height_path": CENTRAL_HIGHLANDS_PATH_HEIGHT,
		"rock_albedo_path": CENTRAL_HIGHLANDS_ROCK_ALBEDO,
		"rock_height_path": CENTRAL_HIGHLANDS_ROCK_HEIGHT,
		"primary_tint": "#c5c58f",
		"secondary_tint": "#a99f7b",
		"path_tint": "#d0ab72",
		"detail_tile": 6.45,
		"secondary_tile_scale": 1.10,
		"path_tile_scale": 0.88,
		"secondary_mask_strength": 0.76,
		"roughness_primary": 0.94,
		"roughness_secondary": 0.98,
		"roughness_path": 0.98,
		"normal_depth": 0.62,
		"spot_edge_raggedness": 0.38,
		"spot_breakup_strength": 0.44,
		"spot_grain_strength": 0.20,
		"spot_core_strength": 0.22,
		"terrain_height_scale": 1.12,
		"terrain_ridge_strength": 1.12,
		"terrain_swell_strength": 1.04,
		"terrain_wadi_strength": 1.18,
		"terrain_ripple_strength": 1.05,
		"terrain_outer_hill_strength": 1.10,
		"terrain_floor": -0.72,
		"terrain_height_offset": 0.08,
		"surface_relief_strength": 1.05,
		"secondary_surface_drop": 0.06,
		"path_color": "#b99459",
		"path_width": 2.25,
		"path_feather": 1.2,
		"path_edge_noise": 0.60,
		"rock_count": 280,
		"rock_scale": 0.92,
		"rock_color": "#a8a18a",
		"rock_texture_tile": 0.46,
		"rock_roughness": 0.98,
		"clump_count": 165,
		"clump_color": "#526f38",
		"clump_height": 0.34,
		"clump_radius": 0.105,
		"wadi_count": 2,
		"wadi_width": 3.35,
		"wadi_color": "#7f6d55",
		"wadi_alpha": 0.32,
		"sky_color": "#64b7f0",
		"fog_color": "#c6d6cf",
		"fog_density": 0.0045,
		"ambient_color": "#e3e3bd",
		"ambient_energy": 0.60,
		"sun_color": "#fff0bd",
		"sun_energy": 2.82,
		"fill_color": "#9ec7ef",
		"fill_energy": 0.34,
		"underlay_color": "#687846"
	},
	4: {
		"biome_key": "galilee_northern_hills",
		"name": "Galilee hills",
		"primary_albedo_path": GALILEE_HILLS_ALBEDO,
		"primary_height_path": GALILEE_HILLS_HEIGHT,
		"secondary_albedo_path": GALILEE_HILLS_SPOTS_ALBEDO,
		"secondary_height_path": GALILEE_HILLS_SPOTS_HEIGHT,
		"path_albedo_path": GALILEE_HILLS_PATH_ALBEDO,
		"path_height_path": GALILEE_HILLS_PATH_HEIGHT,
		"rock_albedo_path": GALILEE_HILLS_ROCK_ALBEDO,
		"rock_height_path": GALILEE_HILLS_ROCK_HEIGHT,
		"primary_tint": "#92ad66",
		"secondary_tint": "#748457",
		"path_tint": "#c7a06b",
		"detail_tile": 6.25,
		"secondary_tile_scale": 1.02,
		"path_tile_scale": 0.86,
		"secondary_mask_strength": 0.74,
		"roughness_primary": 0.94,
		"roughness_secondary": 0.98,
		"roughness_path": 0.98,
		"normal_depth": 0.58,
		"spot_edge_raggedness": 0.44,
		"spot_breakup_strength": 0.52,
		"spot_grain_strength": 0.18,
		"spot_core_strength": 0.30,
		"terrain_height_scale": 0.96,
		"terrain_ridge_strength": 0.90,
		"terrain_swell_strength": 1.08,
		"terrain_wadi_strength": 0.76,
		"terrain_ripple_strength": 0.78,
		"terrain_outer_hill_strength": 0.92,
		"terrain_floor": -0.55,
		"terrain_height_offset": 0.20,
		"surface_relief_strength": 0.95,
		"secondary_surface_drop": 0.045,
		"path_color": "#a88a55",
		"path_width": 2.2,
		"path_feather": 1.35,
		"path_edge_noise": 0.72,
		"rock_count": 210,
		"rock_scale": 0.78,
		"rock_color": "#8d8a74",
		"rock_texture_tile": 0.48,
		"rock_roughness": 0.98,
		"clump_count": 255,
		"clump_color": "#466f35",
		"clump_height": 0.46,
		"clump_radius": 0.13,
		"wadi_count": 1,
		"wadi_width": 3.0,
		"wadi_color": "#6f634c",
		"wadi_alpha": 0.24,
		"sky_color": "#65b8eb",
		"fog_color": "#bed8d2",
		"fog_density": 0.0048,
		"ambient_color": "#dbe5c2",
		"ambient_energy": 0.63,
		"sun_color": "#f7edbb",
		"sun_energy": 2.58,
		"fill_color": "#a5cfec",
		"fill_energy": 0.39,
		"underlay_color": "#3f6435"
	},
	5: {
		"biome_key": "jordan_rift",
		"name": "Jordan Rift",
		"primary_albedo_path": JORDAN_RIFT_ALBEDO,
		"primary_height_path": JORDAN_RIFT_HEIGHT,
		"secondary_albedo_path": JORDAN_RIFT_SPOTS_ALBEDO,
		"secondary_height_path": JORDAN_RIFT_SPOTS_HEIGHT,
		"path_albedo_path": JORDAN_RIFT_PATH_ALBEDO,
		"path_height_path": JORDAN_RIFT_PATH_HEIGHT,
		"rock_albedo_path": JORDAN_RIFT_ROCK_ALBEDO,
		"rock_height_path": JORDAN_RIFT_ROCK_HEIGHT,
		"primary_tint": "#c5b484",
		"secondary_tint": "#d2cfb3",
		"path_tint": "#bfa36e",
		"detail_tile": 5.9,
		"secondary_tile_scale": 1.12,
		"path_tile_scale": 0.86,
		"secondary_mask_strength": 0.58,
		"roughness_primary": 0.96,
		"roughness_secondary": 0.93,
		"roughness_path": 0.98,
		"normal_depth": 0.42,
		"spot_edge_raggedness": 0.34,
		"spot_breakup_strength": 0.34,
		"spot_grain_strength": 0.12,
		"spot_core_strength": 0.18,
		"terrain_height_scale": 0.52,
		"terrain_ridge_strength": 0.32,
		"terrain_swell_strength": 0.48,
		"terrain_wadi_strength": 1.45,
		"terrain_ripple_strength": 0.30,
		"terrain_outer_hill_strength": 0.32,
		"terrain_floor": -1.15,
		"terrain_height_offset": -0.32,
		"surface_relief_strength": 0.58,
		"secondary_surface_drop": 0.045,
		"path_color": "#aa8e5c",
		"path_width": 2.7,
		"path_feather": 1.45,
		"path_edge_noise": 0.46,
		"rock_count": 145,
		"rock_scale": 0.70,
		"rock_color": "#aaa089",
		"rock_texture_tile": 0.50,
		"rock_roughness": 0.99,
		"clump_count": 65,
		"clump_color": "#6e7b58",
		"clump_height": 0.30,
		"clump_radius": 0.10,
		"wadi_count": 2,
		"wadi_width": 4.6,
		"wadi_color": "#7c7660",
		"wadi_alpha": 0.42,
		"sky_color": "#82c5ed",
		"fog_color": "#d0d0bd",
		"fog_density": 0.0052,
		"ambient_color": "#ead7b7",
		"ambient_energy": 0.57,
		"sun_color": "#ffd899",
		"sun_energy": 3.05,
		"fill_color": "#aac5d5",
		"fill_energy": 0.26,
		"underlay_color": "#8d7c58"
	},
	6: {
		"biome_key": "transjordan_plateau",
		"name": "Transjordan plateau",
		"primary_albedo_path": TRANSJORDAN_PLATEAU_ALBEDO,
		"primary_height_path": TRANSJORDAN_PLATEAU_HEIGHT,
		"secondary_albedo_path": TRANSJORDAN_PLATEAU_SPOTS_ALBEDO,
		"secondary_height_path": TRANSJORDAN_PLATEAU_SPOTS_HEIGHT,
		"path_albedo_path": TRANSJORDAN_PLATEAU_PATH_ALBEDO,
		"path_height_path": TRANSJORDAN_PLATEAU_PATH_HEIGHT,
		"rock_albedo_path": TRANSJORDAN_PLATEAU_ROCK_ALBEDO,
		"rock_height_path": TRANSJORDAN_PLATEAU_ROCK_HEIGHT,
		"primary_tint": "#b39b72",
		"secondary_tint": "#8f8068",
		"path_tint": "#b7935d",
		"detail_tile": 6.6,
		"secondary_tile_scale": 1.04,
		"path_tile_scale": 0.88,
		"secondary_mask_strength": 0.76,
		"roughness_primary": 0.98,
		"roughness_secondary": 0.95,
		"roughness_path": 0.98,
		"normal_depth": 0.62,
		"spot_edge_raggedness": 0.42,
		"spot_breakup_strength": 0.44,
		"spot_grain_strength": 0.16,
		"spot_core_strength": 0.24,
		"terrain_height_scale": 0.84,
		"terrain_ridge_strength": 0.76,
		"terrain_swell_strength": 0.70,
		"terrain_wadi_strength": 1.62,
		"terrain_ripple_strength": 0.60,
		"terrain_outer_hill_strength": 0.70,
		"terrain_floor": -0.70,
		"terrain_height_offset": 0.10,
		"surface_relief_strength": 1.05,
		"secondary_surface_drop": 0.075,
		"path_color": "#b1925c",
		"path_width": 2.35,
		"path_feather": 1.2,
		"path_edge_noise": 0.66,
		"rock_count": 285,
		"rock_scale": 1.02,
		"rock_color": "#8c7f68",
		"rock_texture_tile": 0.46,
		"rock_roughness": 0.99,
		"clump_count": 90,
		"clump_color": "#687044",
		"clump_height": 0.34,
		"clump_radius": 0.10,
		"wadi_count": 2,
		"wadi_width": 4.2,
		"wadi_color": "#80684d",
		"wadi_alpha": 0.38,
		"sky_color": "#6fb8e8",
		"fog_color": "#cacdbc",
		"fog_density": 0.0040,
		"ambient_color": "#e3d6ba",
		"ambient_energy": 0.56,
		"sun_color": "#ffe1a3",
		"sun_energy": 2.96,
		"fill_color": "#9fc2db",
		"fill_energy": 0.29,
		"underlay_color": "#74694c"
	},
	7: {
		"biome_key": "negev_arabah_wilderness",
		"name": "Negev wilderness",
		"primary_albedo_path": NEGEV_ARABAH_ALBEDO,
		"primary_height_path": NEGEV_ARABAH_HEIGHT,
		"secondary_albedo_path": NEGEV_ARABAH_SPOTS_ALBEDO,
		"secondary_height_path": NEGEV_ARABAH_SPOTS_HEIGHT,
		"path_albedo_path": NEGEV_ARABAH_PATH_ALBEDO,
		"path_height_path": NEGEV_ARABAH_PATH_HEIGHT,
		"rock_albedo_path": NEGEV_ARABAH_ROCK_ALBEDO,
		"rock_height_path": NEGEV_ARABAH_ROCK_HEIGHT,
		"primary_tint": "#bc8c51",
		"secondary_tint": "#aa7652",
		"path_tint": "#c08c55",
		"detail_tile": 6.8,
		"secondary_tile_scale": 0.96,
		"path_tile_scale": 0.86,
		"secondary_mask_strength": 0.82,
		"roughness_primary": 0.98,
		"roughness_secondary": 0.94,
		"roughness_path": 0.99,
		"normal_depth": 0.66,
		"spot_edge_raggedness": 0.48,
		"spot_breakup_strength": 0.56,
		"spot_grain_strength": 0.22,
		"spot_core_strength": 0.28,
		"terrain_height_scale": 0.92,
		"terrain_ridge_strength": 0.74,
		"terrain_swell_strength": 0.72,
		"terrain_wadi_strength": 1.68,
		"terrain_ripple_strength": 0.88,
		"terrain_outer_hill_strength": 0.86,
		"terrain_vertical_relief_strength": 1.0,
		"terrain_vertical_basin_radius_x": 27.0,
		"terrain_vertical_basin_radius_z": 15.0,
		"terrain_vertical_wall_width": 0.13,
		"terrain_vertical_basin_drop": 1.55,
		"terrain_vertical_rim_height": 2.35,
		"terrain_vertical_wadi_depth": 1.95,
		"terrain_vertical_wadi_floor_width": 2.9,
		"terrain_vertical_wadi_wall_width": 3.2,
		"terrain_vertical_wadi_rim_height": 1.05,
		"terrain_vertical_wadi_meander": 8.4,
		"terrain_vertical_edge_lift": 1.45,
		"terrain_floor": -1.65,
		"terrain_height_offset": -0.06,
		"surface_relief_strength": 1.26,
		"secondary_surface_drop": 0.11,
		"path_color": "#c0975e",
		"path_width": 2.65,
		"path_feather": 1.05,
		"path_edge_noise": 0.54,
		"rock_count": 310,
		"rock_scale": 0.92,
		"rock_color": "#947153",
		"rock_texture_tile": 0.44,
		"rock_roughness": 0.99,
		"clump_count": 42,
		"clump_color": "#74693e",
		"clump_height": 0.28,
		"clump_radius": 0.09,
		"wadi_count": 2,
		"wadi_width": 3.8,
		"wadi_color": "#8f6945",
		"wadi_alpha": 0.34,
		"sky_color": "#77bce8",
		"fog_color": "#dcc9ac",
		"fog_density": 0.0032,
		"ambient_color": "#ecd2ad",
		"ambient_energy": 0.54,
		"sun_color": "#ffd28f",
		"sun_energy": 3.18,
		"fill_color": "#a9bcc8",
		"fill_energy": 0.22,
		"underlay_color": "#947047"
	}
}


static func profile_for_id(biome_id: int) -> Dictionary:
	var selected_id := biome_id if PROFILES.has(biome_id) else DEFAULT_BIOME_ID
	var profile := Dictionary(PROFILES[selected_id]).duplicate(true)
	profile["biome_id"] = selected_id
	return profile


static func has_profile(biome_id: int) -> bool:
	return PROFILES.has(biome_id)
