extends RefCounted

const DEFAULT_BIOME_ID := 3
const TEXTURE_ROOT := "res://assets/textures/terrain"

const BEACH_ALBEDO := "%s/beach/aerial_beach_01_diff_1k.jpg" % TEXTURE_ROOT
const BEACH_HEIGHT := "%s/beach/aerial_beach_01_disp_1k.png" % TEXTURE_ROOT
const FOREST_ALBEDO := "%s/forest_ground/forrest_ground_01_diff_1k.jpg" % TEXTURE_ROOT
const FOREST_HEIGHT := "%s/forest_ground/forrest_ground_01_disp_1k.png" % TEXTURE_ROOT
const MUD_ALBEDO := "%s/mud/brown_mud_leaves_01_diff_1k.jpg" % TEXTURE_ROOT
const MUD_HEIGHT := "%s/mud/brown_mud_leaves_01_disp_1k.png" % TEXTURE_ROOT
const CRACKED_MUD_ALBEDO := "%s/mud_cracked/mud_cracked_dry_03_diff_1k.jpg" % TEXTURE_ROOT
const CRACKED_MUD_HEIGHT := "%s/mud_cracked/mud_cracked_dry_03_disp_1k.png" % TEXTURE_ROOT
const ROCKY_GRASS_ALBEDO := "%s/rocky_grass/rocky_terrain_02_diff_1k.jpg" % TEXTURE_ROOT
const ROCKY_GRASS_HEIGHT := "%s/rocky_grass/rocky_terrain_02_disp_1k.png" % TEXTURE_ROOT
const ROCKY_GRAVEL_ALBEDO := "%s/rocky_gravel/gravelly_sand_diff_1k.jpg" % TEXTURE_ROOT
const ROCKY_GRAVEL_HEIGHT := "%s/rocky_gravel/gravelly_sand_disp_1k.png" % TEXTURE_ROOT
const STONE_ALBEDO := "%s/marble/marble_rock_02_diff_1k.jpg" % TEXTURE_ROOT
const STONE_HEIGHT := "%s/marble/marble_rock_02_disp_1k.png" % TEXTURE_ROOT

const PROFILES := {
	1: {
		"biome_key": "coastal_plain",
		"name": "Coastal plain",
		"primary_albedo_path": BEACH_ALBEDO,
		"primary_height_path": BEACH_HEIGHT,
		"secondary_albedo_path": ROCKY_GRAVEL_ALBEDO,
		"secondary_height_path": ROCKY_GRAVEL_HEIGHT,
		"primary_tint": "#f0d79b",
		"secondary_tint": "#b89f72",
		"detail_tile": 6.35,
		"secondary_tile_scale": 1.08,
		"secondary_mask_strength": 0.56,
		"roughness_primary": 0.92,
		"roughness_secondary": 0.96,
		"normal_depth": 0.38,
		"terrain_height_scale": 0.34,
		"terrain_ridge_strength": 0.24,
		"terrain_swell_strength": 0.42,
		"terrain_wadi_strength": 0.48,
		"terrain_ripple_strength": 0.28,
		"terrain_outer_hill_strength": 0.16,
		"terrain_floor": -0.32,
		"terrain_height_offset": -0.05,
		"surface_relief_strength": 0.58,
		"secondary_surface_drop": 0.035,
		"path_color": "#c9ad70",
		"path_width": 2.8,
		"rock_count": 88,
		"rock_scale": 0.62,
		"rock_color": "#b9aa8c",
		"clump_count": 95,
		"clump_color": "#8a8f54",
		"clump_height": 0.34,
		"clump_radius": 0.10,
		"wadi_count": 0,
		"sky_color": "#80c6f0",
		"fog_color": "#d5e4dc",
		"fog_density": 0.0036,
		"ambient_color": "#eee3c6",
		"ambient_energy": 0.62,
		"sun_color": "#fff1c8",
		"sun_energy": 2.65,
		"fill_color": "#aad1ec",
		"fill_energy": 0.34,
		"underlay_color": "#b99e66"
	},
	2: {
		"biome_key": "shephelah_foothills",
		"name": "Shephelah foothills",
		"primary_albedo_path": ROCKY_GRAVEL_ALBEDO,
		"primary_height_path": ROCKY_GRAVEL_HEIGHT,
		"secondary_albedo_path": ROCKY_GRASS_ALBEDO,
		"secondary_height_path": ROCKY_GRASS_HEIGHT,
		"primary_tint": "#d2b77b",
		"secondary_tint": "#9c9368",
		"detail_tile": 7.1,
		"secondary_tile_scale": 1.16,
		"secondary_mask_strength": 0.78,
		"roughness_primary": 0.94,
		"roughness_secondary": 0.97,
		"normal_depth": 0.52,
		"terrain_height_scale": 0.70,
		"terrain_ridge_strength": 0.58,
		"terrain_swell_strength": 0.88,
		"terrain_wadi_strength": 0.92,
		"terrain_ripple_strength": 0.65,
		"terrain_outer_hill_strength": 0.54,
		"terrain_floor": -0.48,
		"terrain_height_offset": 0.05,
		"surface_relief_strength": 0.90,
		"secondary_surface_drop": 0.065,
		"path_color": "#b89255",
		"path_width": 2.45,
		"rock_count": 185,
		"rock_scale": 0.86,
		"rock_color": "#9d8b70",
		"clump_count": 135,
		"clump_color": "#6f7f43",
		"clump_height": 0.38,
		"clump_radius": 0.12,
		"wadi_count": 1,
		"wadi_width": 3.6,
		"wadi_color": "#9b8056",
		"wadi_alpha": 0.36,
		"sky_color": "#70b9ee",
		"fog_color": "#cbd8c9",
		"fog_density": 0.0042,
		"ambient_color": "#e8ddbd",
		"ambient_energy": 0.58,
		"sun_color": "#ffe6ad",
		"sun_energy": 2.82,
		"fill_color": "#9bc6e7",
		"fill_energy": 0.32,
		"underlay_color": "#8f8153"
	},
	3: {
		"biome_key": "central_highlands",
		"name": "Central highlands",
		"primary_albedo_path": ROCKY_GRASS_ALBEDO,
		"primary_height_path": ROCKY_GRASS_HEIGHT,
		"secondary_albedo_path": ROCKY_GRAVEL_ALBEDO,
		"secondary_height_path": ROCKY_GRAVEL_HEIGHT,
		"primary_tint": "#9c9b69",
		"secondary_tint": "#8f8066",
		"detail_tile": 7.33,
		"secondary_tile_scale": 1.20,
		"secondary_mask_strength": 0.88,
		"roughness_primary": 0.94,
		"roughness_secondary": 0.98,
		"normal_depth": 0.55,
		"terrain_height_scale": 1.0,
		"terrain_ridge_strength": 1.0,
		"terrain_swell_strength": 1.0,
		"terrain_wadi_strength": 1.0,
		"terrain_ripple_strength": 1.0,
		"terrain_outer_hill_strength": 1.0,
		"terrain_floor": -0.55,
		"terrain_height_offset": 0.0,
		"surface_relief_strength": 1.0,
		"secondary_surface_drop": 0.09,
		"path_color": "#c0a56d",
		"path_width": 2.4,
		"rock_count": 240,
		"rock_scale": 1.0,
		"rock_color": "#8f8877",
		"clump_count": 110,
		"clump_color": "#5f6f39",
		"clump_height": 0.32,
		"clump_radius": 0.10,
		"wadi_count": 1,
		"wadi_width": 3.1,
		"wadi_color": "#7f6d55",
		"wadi_alpha": 0.28,
		"sky_color": "#64b7f0",
		"fog_color": "#c2d8e6",
		"fog_density": 0.0045,
		"ambient_color": "#e8e0c5",
		"ambient_energy": 0.58,
		"sun_color": "#fff0bd",
		"sun_energy": 2.9,
		"fill_color": "#9ec7ef",
		"fill_energy": 0.32,
		"underlay_color": "#596f3c"
	},
	4: {
		"biome_key": "galilee_northern_hills",
		"name": "Galilee hills",
		"primary_albedo_path": FOREST_ALBEDO,
		"primary_height_path": FOREST_HEIGHT,
		"secondary_albedo_path": ROCKY_GRASS_ALBEDO,
		"secondary_height_path": ROCKY_GRASS_HEIGHT,
		"primary_tint": "#7ea163",
		"secondary_tint": "#8c8f65",
		"detail_tile": 7.8,
		"secondary_tile_scale": 1.12,
		"secondary_mask_strength": 0.70,
		"roughness_primary": 0.91,
		"roughness_secondary": 0.96,
		"normal_depth": 0.50,
		"terrain_height_scale": 0.88,
		"terrain_ridge_strength": 0.86,
		"terrain_swell_strength": 1.04,
		"terrain_wadi_strength": 0.78,
		"terrain_ripple_strength": 0.82,
		"terrain_outer_hill_strength": 0.86,
		"terrain_floor": -0.50,
		"terrain_height_offset": 0.18,
		"surface_relief_strength": 0.82,
		"secondary_surface_drop": 0.055,
		"path_color": "#a88e54",
		"path_width": 2.25,
		"rock_count": 190,
		"rock_scale": 0.82,
		"rock_color": "#76806f",
		"clump_count": 190,
		"clump_color": "#4f783b",
		"clump_height": 0.45,
		"clump_radius": 0.13,
		"wadi_count": 0,
		"sky_color": "#65b8eb",
		"fog_color": "#bed8d2",
		"fog_density": 0.0048,
		"ambient_color": "#dfe3c4",
		"ambient_energy": 0.60,
		"sun_color": "#f7edbb",
		"sun_energy": 2.72,
		"fill_color": "#a5cfec",
		"fill_energy": 0.36,
		"underlay_color": "#536f3e"
	},
	5: {
		"biome_key": "jordan_rift",
		"name": "Jordan Rift",
		"primary_albedo_path": MUD_ALBEDO,
		"primary_height_path": MUD_HEIGHT,
		"secondary_albedo_path": BEACH_ALBEDO,
		"secondary_height_path": BEACH_HEIGHT,
		"primary_tint": "#b9a277",
		"secondary_tint": "#d2bd87",
		"detail_tile": 6.65,
		"secondary_tile_scale": 1.28,
		"secondary_mask_strength": 0.62,
		"roughness_primary": 0.96,
		"roughness_secondary": 0.93,
		"normal_depth": 0.34,
		"terrain_height_scale": 0.48,
		"terrain_ridge_strength": 0.32,
		"terrain_swell_strength": 0.48,
		"terrain_wadi_strength": 1.35,
		"terrain_ripple_strength": 0.30,
		"terrain_outer_hill_strength": 0.32,
		"terrain_floor": -1.15,
		"terrain_height_offset": -0.32,
		"surface_relief_strength": 0.52,
		"secondary_surface_drop": 0.045,
		"path_color": "#aa8e5c",
		"path_width": 2.7,
		"rock_count": 126,
		"rock_scale": 0.72,
		"rock_color": "#9a8b75",
		"clump_count": 55,
		"clump_color": "#6e7b58",
		"clump_height": 0.30,
		"clump_radius": 0.10,
		"wadi_count": 2,
		"wadi_width": 4.6,
		"wadi_color": "#7c7660",
		"wadi_alpha": 0.42,
		"sky_color": "#82c5ed",
		"fog_color": "#d0d0bd",
		"fog_density": 0.0052,
		"ambient_color": "#ead7b7",
		"ambient_energy": 0.57,
		"sun_color": "#ffd899",
		"sun_energy": 3.05,
		"fill_color": "#aac5d5",
		"fill_energy": 0.26,
		"underlay_color": "#8d7c58"
	},
	6: {
		"biome_key": "transjordan_plateau",
		"name": "Transjordan plateau",
		"primary_albedo_path": STONE_ALBEDO,
		"primary_height_path": STONE_HEIGHT,
		"secondary_albedo_path": ROCKY_GRAVEL_ALBEDO,
		"secondary_height_path": ROCKY_GRAVEL_HEIGHT,
		"primary_tint": "#a3916f",
		"secondary_tint": "#b99b66",
		"detail_tile": 7.55,
		"secondary_tile_scale": 1.05,
		"secondary_mask_strength": 0.72,
		"roughness_primary": 0.98,
		"roughness_secondary": 0.95,
		"normal_depth": 0.57,
		"terrain_height_scale": 0.78,
		"terrain_ridge_strength": 0.72,
		"terrain_swell_strength": 0.68,
		"terrain_wadi_strength": 1.70,
		"terrain_ripple_strength": 0.58,
		"terrain_outer_hill_strength": 0.66,
		"terrain_floor": -0.70,
		"terrain_height_offset": 0.10,
		"surface_relief_strength": 1.05,
		"secondary_surface_drop": 0.075,
		"path_color": "#b1925c",
		"path_width": 2.35,
		"rock_count": 260,
		"rock_scale": 1.08,
		"rock_color": "#8d806d",
		"clump_count": 82,
		"clump_color": "#687044",
		"clump_height": 0.34,
		"clump_radius": 0.10,
		"wadi_count": 2,
		"wadi_width": 4.2,
		"wadi_color": "#80684d",
		"wadi_alpha": 0.38,
		"sky_color": "#6fb8e8",
		"fog_color": "#cacdbc",
		"fog_density": 0.0040,
		"ambient_color": "#e3d6ba",
		"ambient_energy": 0.56,
		"sun_color": "#ffe1a3",
		"sun_energy": 2.96,
		"fill_color": "#9fc2db",
		"fill_energy": 0.29,
		"underlay_color": "#74694c"
	},
	7: {
		"biome_key": "negev_arabah_wilderness",
		"name": "Negev wilderness",
		"primary_albedo_path": CRACKED_MUD_ALBEDO,
		"primary_height_path": CRACKED_MUD_HEIGHT,
		"secondary_albedo_path": ROCKY_GRAVEL_ALBEDO,
		"secondary_height_path": ROCKY_GRAVEL_HEIGHT,
		"primary_tint": "#c09b65",
		"secondary_tint": "#dfc38a",
		"detail_tile": 7.0,
		"secondary_tile_scale": 1.34,
		"secondary_mask_strength": 0.82,
		"roughness_primary": 0.98,
		"roughness_secondary": 0.94,
		"normal_depth": 0.62,
		"terrain_height_scale": 0.62,
		"terrain_ridge_strength": 0.54,
		"terrain_swell_strength": 0.54,
		"terrain_wadi_strength": 1.25,
		"terrain_ripple_strength": 0.86,
		"terrain_outer_hill_strength": 0.44,
		"terrain_floor": -0.68,
		"terrain_height_offset": -0.10,
		"surface_relief_strength": 1.18,
		"secondary_surface_drop": 0.11,
		"path_color": "#c0975e",
		"path_width": 2.65,
		"rock_count": 310,
		"rock_scale": 0.92,
		"rock_color": "#967152",
		"clump_count": 42,
		"clump_color": "#74693e",
		"clump_height": 0.28,
		"clump_radius": 0.09,
		"wadi_count": 2,
		"wadi_width": 3.8,
		"wadi_color": "#8f6945",
		"wadi_alpha": 0.34,
		"sky_color": "#77bce8",
		"fog_color": "#dcc9ac",
		"fog_density": 0.0032,
		"ambient_color": "#ecd2ad",
		"ambient_energy": 0.54,
		"sun_color": "#ffd28f",
		"sun_energy": 3.18,
		"fill_color": "#a9bcc8",
		"fill_energy": 0.22,
		"underlay_color": "#947047"
	}
}


static func profile_for_id(biome_id: int) -> Dictionary:
	var selected_id := biome_id if PROFILES.has(biome_id) else DEFAULT_BIOME_ID
	var profile := Dictionary(PROFILES[selected_id]).duplicate(true)
	profile["biome_id"] = selected_id
	return profile


static func has_profile(biome_id: int) -> bool:
	return PROFILES.has(biome_id)
